---
title: "EDLD3-midterm"
author: "Raleigh Goodwin, Vinita Vader, Shijing Zhou"
date: "4/21/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

```

```{r, echo=FALSE, message=FALSE}
library(glue)
library(purrr)
library(tidyverse)
library(lubridate)
library(janitor)
library(gapr)
library(ggtext)
library(stringr)
```

# Part A: Data 
```{r}
download_file <- function(year) {
  link <- glue::glue("https://www.oregon.gov/ode/educator-resources/assessment/TestResults20{year}/pagr_schools_ela_raceethnicity_{year-1}{year}.xlsx")
  rio::import(link, setclass = "tibble", na = c("-", "--", "*"))
}
```

## 1.
```{r}
data = map_df(15:18, download_file)
#View(data)
```

Conduct some basic data cleaning to make your data file look like the following.
```{r}
clean.data = data %>% 
  #Filter for only student groups coded as "White" or "Hispanic/Latino".
     filter(`Student Group` %in% c("White", "Hispanic/Latino")) %>% 
  #Select variables related to the number of students in each of the levels (1:4), and not percentages or collapsed levels.
     dplyr::select(`Academic Year` ,`District`, `School`, `Student Group`, `Grade Level`,`Number Level 1` ,  `Number Level 2`,`Number Level 3`, `Number Level 4` ) %>% 
     clean_names() %>% 
 # mutate(n = map(data,nrow)) - doesn't work because var selection needed
 pivot_longer(number_level_1:number_level_4, names_to = "level", values_to = "n") %>% 
  #Remove any row that has missing data in any of the n variables
  drop_na() %>% 
  mutate(level = parse_number(level)) %>% 
  mutate(level = as.character(level), 
         n = as.integer(n))
  
clean.data
```

## 2. 

```{r}
clean.data_2 <- clean.data %>%  
   group_by(district) %>% 
  mutate(n_schools = length(unique(school))) %>% 
  group_by(academic_year, district, student_group, level, n_schools) %>%
  summarize(n = sum(n)) %>% pivot_wider(names_from = student_group, values_from = n) %>%
  drop_na() %>%
  arrange(district) %>% 
   janitor::clean_names() %>% 
   select(academic_year, district, n_schools,  everything())

clean.data_2
```


# Part B: Achievement gaps

## 1.
```{r}
nested <- clean.data_2 %>% 
  group_by(district, academic_year) %>% 
  nest() 

results_1 <- nested %>% 
  mutate(gap = map(data, ~estimate_v(data = .x, "white", "hispanic_latino")))

results_1 <- results_1 %>% 
  mutate(missing = map_lgl(gap, ~ nrow(.x)==0)) %>% 
  filter(missing == FALSE)

results_2 <- clean.data_2 %>% 
  ungroup() %>% 
  nest_by(district, academic_year) %>% 
  summarize(gap = list(estimate_v(data, "white", "hispanic_latino")))

results_2 <- results_2 %>% 
  mutate(missing = map_lgl(gap, ~ nrow(.x)==0)) %>% 
  filter(missing == FALSE)
```

## 2. 
```{r}
plot <- left_join(results_1, results_2, by = c("district", "academic_year")) 

plot <- plot %>% 
  mutate(v_1 = map_dbl(gap.x, "v"),
         v_2 = map_dbl(gap.y, "v"))

plot %>% 
  ggplot(aes(x = v_1, y = v_2)) + 
  geom_line(size = 1, 
            color = "lightskyblue") +
  geom_point(alpha = 0.3,
             color = "azure4") +
  labs(x = "Method 1: map", 
       y = "Method 2: rowwise") +
  scale_y_continuous(breaks = c(-1, 0, 1)) +
  theme_bw()
```

## 3.
```{r}
dists <- unique(results_2$district)[1:100]

needn <- clean.data_2 %>% 
  group_by(district, academic_year) %>% 
  nest()

schoolnum <- as.data.frame(rep(NA, nrow(needn))) %>%
  mutate(district = needn$district) %>% 
  rename(nschool = `rep(NA, nrow(needn))`)

for(i in 1:nrow(needn)){
  schoolnum$nschool[i] <- needn$data[[i]]$n_schools
}

schoolnum <- schoolnum %>% 
  distinct()

plot2n <- left_join(schoolnum, results_2)

plot2n <- plot2n %>% 
  filter(district %in% dists)

plot2n <- plot2n %>% 
  mutate(v = map_dbl(gap, "v"),
         posneg = if_else(v < 0, "darkorchid2", "dodgerblue2")) %>% 
  group_by(academic_year) %>% 
  mutate(mean_v = mean(v),
         se_v = sd(v/sqrt(n()))) %>% 
  ungroup()

plot2n$district <- map_chr(plot2n$district, ~sub(" SD *.*[0-9]", "", .x)) # this isn't working quite right, and I'm not sure why. I'm trying to extract just the school district name, but it's not extracting everything after "SD" like I thought it would

# trying with one district first
plot2ntry <- plot2n[26:29,]
  
plot2ntry %>% 
  ggplot(aes(x = academic_year, y = v)) +
  geom_line() +
  geom_point(color = plot2ntry$posneg) +
  geom_errorbar(aes(ymin = v + qnorm(0.025)*se_v,
                    ymax = v + qnorm(0.975)*se_v),
                width = .3,
                size = .7) +
  geom_hline(yintercept = 0, color = "red") +
  labs(title = "Achievement Gap Estimates: ??? School District",
       subtitle = "Negative values indicate
       <span style='color:darkorchid2'>**White**</span> 
       <span style='color:black'>students have higher average achievement</span> 
       <br>
       <span style='color:black'>Positive values indicate</span>
       <span style='color:dodgerblue2'>**Hispanic/Latino**</span>
       <span style='color:black'>students have higher average achievement</span>
       </span>",
       x = "School year",
       y = "Average achievement difference (SD units)",
       caption = "Note: District included ??? schools.") +
  theme_bw() +
  theme(legend.position = "none",
        plot.subtitle = element_markdown())

# generalize to 100

p2 <- plot2n %>% 
  group_by(district) %>% 
  nest() %>% 
  mutate(plot = map2(data, district, ~{
  ggplot(.x, aes(x = academic_year, y = v, group = 1)) +
  geom_line(color = "gray65",
            size = .7) +
  geom_errorbar(aes(ymin = v + qnorm(0.025)*se_v,
                    ymax = v + qnorm(0.975)*se_v),
                width = .3,
                size = .8,
                color = "gray65") +
  geom_point(color = .x$posneg,
             size = 2) +
  geom_hline(yintercept = 0, color = "red") +
  labs(title = glue("Achievement Gap Estimates: {.y} School District"),
       subtitle = "Negative values indicate
       <span style='color:darkorchid2'>**White**</span> 
       <span style='color:black'>students have higher average achievement</span> 
       <br>
       <span style='color:black'>Positive values indicate</span>
       <span style='color:dodgerblue2'>**Hispanic/Latino**</span>
       <span style='color:black'>students have higher average achievement</span>
       </span>",
       x = "School year",
       y = "Average achievement difference (SD units)",
       caption = glue("Note: District included {.x$nschool} schools.")) +
  theme_bw() +
  theme(legend.position = "none",
        plot.subtitle = element_markdown())
  })
)

p2$plot[[1]]
p2$plot[[5]]
p2$plot[[8]]
```

## 4.
```{r}
dir.create(here::here("plots"))

file_names <- here::here("plots",
                        paste0(p2$district, "_District_Gap_Plot.png")) # They save funky because I really want the `district` strings to be truncated, but I can't figure it out.

invisible(mapply(ggsave, file = file_names, plot = p2$plot, device = "png"))
```
